-- Migration 011: Complete Exercise Library Part 2
-- Arms (Biceps/Triceps 25), Legs (40), Core (25) = 90 exercises

-- ============================================
-- BICEPS EXERCISES (12)
-- ============================================

INSERT INTO exercises (name, slug, description, instructions, cues, common_mistakes, primary_muscles, secondary_muscles, equipment_names, difficulty, movement_pattern, exercise_type, video_url, is_machine, is_bilateral, is_published)
VALUES
('Barbell Curl', 'barbell-curl', 'The classic biceps builder for mass.',
 ARRAY['Stand with barbell at thighs', 'Curl bar up to shoulders', 'Squeeze at top', 'Lower with control'],
 ARRAY['Keep elbows pinned', 'No swinging', 'Full range of motion'],
 ARRAY['Swinging body', 'Moving elbows forward', 'Partial reps'],
 ARRAY['biceps'], ARRAY['forearms', 'brachialis'], ARRAY['barbell'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/BqKpNxLe0TW7rd', false, true, true),

('EZ Bar Curl', 'ez-bar-curl', 'Wrist-friendly barbell curl alternative.',
 ARRAY['Grip EZ bar at angled portions', 'Curl up to shoulders', 'Squeeze at top', 'Lower with control'],
 ARRAY['Wrists stay neutral', 'Elbows pinned', 'Full contraction'],
 ARRAY['Swinging', 'Incomplete range', 'Going too heavy'],
 ARRAY['biceps'], ARRAY['forearms', 'brachialis'], ARRAY['ez curl bar'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/CqKpNxLe0TW7rd', false, true, true),

('Dumbbell Curl', 'dumbbell-curl', 'Unilateral biceps work for balanced development.',
 ARRAY['Stand with dumbbells at sides', 'Curl up rotating palms up', 'Squeeze at top', 'Lower with control'],
 ARRAY['Supinate at top', 'Control negative', 'Alternate or together'],
 ARRAY['Swinging', 'Using momentum', 'Incomplete range'],
 ARRAY['biceps'], ARRAY['forearms', 'brachialis'], ARRAY['dumbbells'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/DqKpNxLe0TW7rd', false, true, true),

('Hammer Curl', 'hammer-curl', 'Target brachialis and forearms with neutral grip.',
 ARRAY['Hold dumbbells with palms facing each other', 'Curl up keeping neutral grip', 'Lower with control', 'Keep elbows fixed'],
 ARRAY['Neutral grip throughout', 'Squeeze at top', 'Control the weight'],
 ARRAY['Swinging', 'Moving elbows', 'Rushing reps'],
 ARRAY['brachialis', 'forearms'], ARRAY['biceps'], ARRAY['dumbbells'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/EqKpNxLe0TW7rd', false, true, true),

('Preacher Curl', 'preacher-curl', 'Strict biceps isolation eliminating momentum.',
 ARRAY['Sit at preacher bench', 'Rest arms on pad', 'Curl weight up', 'Lower with control'],
 ARRAY['Keep arms flat on pad', 'Full extension', 'Squeeze at top'],
 ARRAY['Lifting elbows', 'Partial reps', 'Going too heavy'],
 ARRAY['biceps'], ARRAY['brachialis'], ARRAY['ez curl bar', 'preacher curl bench'],
 'intermediate', 'isolation', 'strength', 'https://v2.exercisedb.io/image/FqKpNxLe0TW7rd', false, true, true),

('Incline Dumbbell Curl', 'incline-dumbbell-curl', 'Extended stretch for full biceps development.',
 ARRAY['Lie back on incline bench', 'Let arms hang with dumbbells', 'Curl up', 'Lower with control'],
 ARRAY['Let arms hang straight', 'Full stretch at bottom', 'Squeeze at top'],
 ARRAY['Cutting range short', 'Moving elbows forward', 'Too heavy'],
 ARRAY['biceps long head'], ARRAY['brachialis'], ARRAY['dumbbells', 'incline bench'],
 'intermediate', 'isolation', 'strength', 'https://v2.exercisedb.io/image/GqKpNxLe0TW7rd', false, true, true),

('Concentration Curl', 'concentration-curl', 'Peak contraction biceps exercise.',
 ARRAY['Sit with elbow braced against inner thigh', 'Curl dumbbell up', 'Squeeze at top', 'Lower with control'],
 ARRAY['Brace elbow firmly', 'Peak contraction', 'No swinging'],
 ARRAY['Moving elbow', 'Not squeezing at top', 'Rushing'],
 ARRAY['biceps'], ARRAY['brachialis'], ARRAY['dumbbell'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/HqKpNxLe0TW7rd', false, false, true),

('Cable Curl', 'cable-curl', 'Constant tension biceps isolation.',
 ARRAY['Stand facing cable with bar attached low', 'Curl bar to shoulders', 'Squeeze at top', 'Lower with control'],
 ARRAY['Constant tension', 'Elbows fixed', 'Full range'],
 ARRAY['Swinging body', 'Moving elbows', 'Cutting range'],
 ARRAY['biceps'], ARRAY['brachialis', 'forearms'], ARRAY['cable machine'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/IqKpNxLe0TW7rd', false, true, true),

('Spider Curl', 'spider-curl', 'Strict curl with unique angle.',
 ARRAY['Lie face down on incline bench', 'Let arms hang with dumbbells', 'Curl up against gravity', 'Lower with control'],
 ARRAY['Arms hang straight down', 'Full contraction', 'Control negative'],
 ARRAY['Swinging', 'Incomplete range', 'Going too fast'],
 ARRAY['biceps short head'], ARRAY['brachialis'], ARRAY['dumbbells', 'incline bench'],
 'intermediate', 'isolation', 'strength', 'https://v2.exercisedb.io/image/JqKpNxLe0TW7rd', false, true, true),

('Reverse Curl', 'reverse-curl', 'Target brachialis and forearm extensors.',
 ARRAY['Grip bar with palms down', 'Curl up keeping overhand grip', 'Lower with control', 'Keep wrists straight'],
 ARRAY['Overhand grip throughout', 'Controlled motion', 'Feel forearms working'],
 ARRAY['Flexing wrists', 'Going too heavy', 'Swinging'],
 ARRAY['brachialis', 'forearm extensors'], ARRAY['biceps'], ARRAY['barbell', 'ez curl bar'],
 'intermediate', 'isolation', 'strength', 'https://v2.exercisedb.io/image/KqKpNxLe0TW7rd', false, true, true),

('21s', 'twenty-ones', 'Biceps finisher with three ranges of motion.',
 ARRAY['7 reps bottom half', '7 reps top half', '7 reps full range', 'No rest between'],
 ARRAY['Strict form', 'Feel the burn', 'Continuous tension'],
 ARRAY['Going too heavy', 'Cheating on later reps', 'Resting between portions'],
 ARRAY['biceps'], ARRAY['brachialis', 'forearms'], ARRAY['barbell', 'dumbbells'],
 'intermediate', 'isolation', 'strength', 'https://v2.exercisedb.io/image/LqKpNxLe0TW7rd', false, true, true),

('Machine Preacher Curl', 'machine-preacher-curl', 'Guided preacher curl motion.',
 ARRAY['Adjust seat height', 'Rest arms on pad', 'Curl handles up', 'Lower with control'],
 ARRAY['Keep arms on pad', 'Full range of motion', 'Squeeze at top'],
 ARRAY['Lifting elbows', 'Partial range', 'Rushing'],
 ARRAY['biceps'], ARRAY['brachialis'], ARRAY['preacher curl machine'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/MqKpNxLe0TW7rd', true, true, true);

-- ============================================
-- TRICEPS EXERCISES (13)
-- ============================================

INSERT INTO exercises (name, slug, description, instructions, cues, common_mistakes, primary_muscles, secondary_muscles, equipment_names, difficulty, movement_pattern, exercise_type, video_url, is_machine, is_bilateral, is_published)
VALUES
('Skull Crusher', 'skull-crusher', 'Lying triceps extension for mass.',
 ARRAY['Lie on bench with bar above chest', 'Lower bar to forehead', 'Extend arms back up', 'Keep elbows pointed up'],
 ARRAY['Elbows stay fixed', 'Control the negative', 'Full extension'],
 ARRAY['Flaring elbows', 'Going too heavy', 'Dropping weight to face'],
 ARRAY['triceps'], ARRAY['forearms'], ARRAY['barbell', 'ez curl bar', 'bench'],
 'intermediate', 'isolation', 'strength', 'https://v2.exercisedb.io/image/NqKpMxLe0TW7rd', false, true, true),

('Triceps Pushdown', 'triceps-pushdown', 'Classic cable triceps isolation.',
 ARRAY['Stand at cable with bar or rope', 'Push down until arms straight', 'Squeeze at bottom', 'Return with control'],
 ARRAY['Elbows pinned to sides', 'Full extension', 'Squeeze triceps'],
 ARRAY['Moving elbows', 'Leaning over bar', 'Using momentum'],
 ARRAY['triceps'], ARRAY['forearms'], ARRAY['cable machine'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/OqKpNxLe0TW7rd', false, true, true),

('Rope Pushdown', 'rope-pushdown', 'Triceps pushdown with rope for extra contraction.',
 ARRAY['Grip rope at cable station', 'Push down spreading rope apart', 'Squeeze at bottom', 'Return with control'],
 ARRAY['Spread rope at bottom', 'Elbows fixed', 'Peak contraction'],
 ARRAY['Not spreading rope', 'Moving elbows', 'Cutting range'],
 ARRAY['triceps'], ARRAY['forearms'], ARRAY['cable machine', 'rope'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/PqKpNxLe0TW7rd', false, true, true),

('Overhead Triceps Extension', 'overhead-triceps-extension', 'Target triceps long head with overhead stretch.',
 ARRAY['Hold dumbbell or bar overhead', 'Lower behind head', 'Extend back to start', 'Keep upper arms vertical'],
 ARRAY['Elbows point up', 'Full stretch at bottom', 'Full extension at top'],
 ARRAY['Flaring elbows', 'Moving upper arms', 'Going too heavy'],
 ARRAY['triceps long head'], ARRAY['forearms'], ARRAY['dumbbell', 'ez curl bar'],
 'intermediate', 'isolation', 'strength', 'https://v2.exercisedb.io/image/QqKpNxLe0TW7rd', false, true, true),

('Dip (Triceps)', 'dip-triceps', 'Compound triceps and chest builder.',
 ARRAY['Mount dip bars with straight arms', 'Keep torso upright', 'Lower until upper arms parallel', 'Press back up'],
 ARRAY['Stay upright for triceps', 'Elbows track back', 'Full lockout'],
 ARRAY['Leaning too forward', 'Partial range', 'Swinging'],
 ARRAY['triceps'], ARRAY['anterior deltoid', 'chest'], ARRAY['dip station'],
 'intermediate', 'push', 'strength', 'https://v2.exercisedb.io/image/RqKpNxLe0TW7rd', false, true, true),

('Diamond Push-up', 'diamond-pushup-triceps', 'Bodyweight triceps emphasis push-up.',
 ARRAY['Hands together forming diamond', 'Lower chest to hands', 'Push back up', 'Keep elbows close'],
 ARRAY['Elbows track to sides', 'Core engaged', 'Full range'],
 ARRAY['Flaring elbows', 'Sagging hips', 'Partial reps'],
 ARRAY['triceps'], ARRAY['chest', 'anterior deltoid'], ARRAY['bodyweight'],
 'intermediate', 'push', 'strength', 'https://v2.exercisedb.io/image/SqKpNxLe0TW7rd', false, true, true),

('Kickback', 'triceps-kickback', 'Triceps isolation with peak contraction.',
 ARRAY['Bend over with upper arm parallel to floor', 'Extend forearm back', 'Squeeze at top', 'Lower with control'],
 ARRAY['Upper arm stays fixed', 'Full extension', 'Squeeze at top'],
 ARRAY['Swinging', 'Dropping upper arm', 'Going too heavy'],
 ARRAY['triceps'], ARRAY['forearms'], ARRAY['dumbbell'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/TqKpNxLe0TW7rd', false, false, true),

('Close Grip Bench', 'close-grip-bench-triceps', 'Compound pressing for triceps mass.',
 ARRAY['Grip bar at shoulder width', 'Lower to lower chest', 'Press up with triceps', 'Keep elbows tucked'],
 ARRAY['Elbows close to body', 'Full lockout', 'Control the bar'],
 ARRAY['Grip too narrow', 'Flaring elbows', 'Bouncing'],
 ARRAY['triceps'], ARRAY['chest', 'anterior deltoid'], ARRAY['barbell', 'bench'],
 'intermediate', 'push', 'strength', 'https://v2.exercisedb.io/image/UqKpNxLe0TW7rd', false, true, true),

('JM Press', 'jm-press', 'Hybrid skull crusher and close grip press.',
 ARRAY['Lie on bench with close grip', 'Lower bar toward throat', 'Press up and back', 'Keep elbows pointing up and forward'],
 ARRAY['Elbows track forward', 'Control throughout', 'Full lockout'],
 ARRAY['Going too heavy', 'Bar path too vertical', 'Losing control'],
 ARRAY['triceps'], ARRAY['chest', 'anterior deltoid'], ARRAY['barbell', 'bench'],
 'advanced', 'push', 'strength', 'https://v2.exercisedb.io/image/VqKpNxLe0TW7rd', false, true, true),

('Cable Overhead Extension', 'cable-overhead-extension', 'Constant tension overhead triceps work.',
 ARRAY['Face away from low cable', 'Grip rope overhead', 'Extend arms forward', 'Return with control'],
 ARRAY['Upper arms stay fixed', 'Full extension', 'Control negative'],
 ARRAY['Moving upper arms', 'Arching back', 'Rushing'],
 ARRAY['triceps long head'], ARRAY['forearms'], ARRAY['cable machine', 'rope'],
 'intermediate', 'isolation', 'strength', 'https://v2.exercisedb.io/image/WqKpNxLe0TW7rd', false, true, true),

('Bench Dip', 'bench-dip', 'Bodyweight triceps exercise using bench.',
 ARRAY['Hands on bench behind you', 'Feet on floor or elevated', 'Lower body by bending arms', 'Press back up'],
 ARRAY['Keep back close to bench', 'Go deep for stretch', 'Full lockout'],
 ARRAY['Shallow range', 'Rounding shoulders', 'Going too fast'],
 ARRAY['triceps'], ARRAY['anterior deltoid', 'chest'], ARRAY['bench'],
 'beginner', 'push', 'strength', 'https://v2.exercisedb.io/image/XqKpNxLe0TW7rd', false, true, true),

('Machine Triceps Dip', 'machine-triceps-dip', 'Assisted dip machine for triceps.',
 ARRAY['Set weight and grip handles', 'Push down until arms straight', 'Return with control', 'Keep upright position'],
 ARRAY['Stay upright', 'Full extension', 'Control negative'],
 ARRAY['Leaning forward', 'Partial range', 'Too much weight'],
 ARRAY['triceps'], ARRAY['chest', 'anterior deltoid'], ARRAY['dip machine'],
 'beginner', 'push', 'strength', 'https://v2.exercisedb.io/image/YqKpNxLe0TW7rd', true, true, true),

('Tate Press', 'tate-press', 'Unique dumbbell triceps exercise.',
 ARRAY['Lie on bench with dumbbells above chest', 'Lower dumbbells in arc to chest', 'Extend back to start', 'Keep elbows pointing out'],
 ARRAY['Elbows flare out', 'Dumbbells touch chest', 'Extend with triceps'],
 ARRAY['Too much weight', 'Not enough range', 'Rushing'],
 ARRAY['triceps'], ARRAY['forearms'], ARRAY['dumbbells', 'bench'],
 'intermediate', 'isolation', 'strength', 'https://v2.exercisedb.io/image/ZqKpNxLe0TW7rd', false, true, true);

-- ============================================
-- LEG EXERCISES (40)
-- ============================================

INSERT INTO exercises (name, slug, description, instructions, cues, common_mistakes, primary_muscles, secondary_muscles, equipment_names, difficulty, movement_pattern, exercise_type, video_url, is_machine, is_bilateral, is_published)
VALUES
-- Quad Dominant
('Barbell Back Squat', 'barbell-back-squat', 'The king of leg exercises for total lower body development.',
 ARRAY['Bar on upper back', 'Feet shoulder width apart', 'Squat until thighs parallel or below', 'Drive up through heels'],
 ARRAY['Chest up', 'Knees track toes', 'Full depth'],
 ARRAY['Heels rising', 'Knees caving', 'Rounding back'],
 ARRAY['quads', 'glutes'], ARRAY['hamstrings', 'core', 'lower back'], ARRAY['barbell', 'squat rack'],
 'intermediate', 'squat', 'strength', 'https://v2.exercisedb.io/image/AqKpNxLe0TW8rd', false, true, true),

('Front Squat', 'front-squat', 'Quad-focused squat with upright torso.',
 ARRAY['Bar in front rack position', 'Elbows high', 'Squat deep keeping upright', 'Drive up'],
 ARRAY['Elbows stay up', 'Upright torso', 'Full depth'],
 ARRAY['Elbows dropping', 'Forward lean', 'Cutting depth'],
 ARRAY['quads'], ARRAY['core', 'glutes', 'upper back'], ARRAY['barbell', 'squat rack'],
 'advanced', 'squat', 'strength', 'https://v2.exercisedb.io/image/BqKpNxLe0TW8rd', false, true, true),

('Goblet Squat', 'goblet-squat', 'Beginner-friendly squat with weight in front.',
 ARRAY['Hold dumbbell at chest', 'Squat between knees', 'Keep chest up', 'Drive up through heels'],
 ARRAY['Elbows inside knees', 'Upright torso', 'Full depth'],
 ARRAY['Rounding back', 'Heels rising', 'Shallow depth'],
 ARRAY['quads', 'glutes'], ARRAY['core', 'hamstrings'], ARRAY['dumbbell', 'kettlebell'],
 'beginner', 'squat', 'strength', 'https://v2.exercisedb.io/image/CqKpNxLe0TW8rd', false, true, true),

('Hack Squat', 'hack-squat', 'Machine squat variation for quad focus.',
 ARRAY['Position shoulders under pads', 'Feet forward on platform', 'Squat down deep', 'Push back up'],
 ARRAY['Full depth', 'Control descent', 'Drive through heels'],
 ARRAY['Partial reps', 'Bouncing at bottom', 'Locking out hard'],
 ARRAY['quads'], ARRAY['glutes', 'hamstrings'], ARRAY['hack squat machine'],
 'intermediate', 'squat', 'strength', 'https://v2.exercisedb.io/image/DqKpNxLe0TW8rd', true, true, true),

('Leg Press', 'leg-press', 'Safe heavy loading for legs.',
 ARRAY['Sit in leg press machine', 'Feet shoulder width on platform', 'Lower weight with control', 'Press back up without locking knees'],
 ARRAY['Full range of motion', 'Lower back stays on pad', 'Control the weight'],
 ARRAY['Locking knees', 'Back lifting off pad', 'Bouncing'],
 ARRAY['quads'], ARRAY['glutes', 'hamstrings'], ARRAY['leg press machine'],
 'beginner', 'squat', 'strength', 'https://v2.exercisedb.io/image/EqKpNxLe0TW8rd', true, true, true),

('Bulgarian Split Squat', 'bulgarian-split-squat', 'Single leg squat for balance and hypertrophy.',
 ARRAY['Rear foot elevated on bench', 'Lower until rear knee near floor', 'Drive up through front heel', 'Keep torso upright'],
 ARRAY['Front knee tracks toe', 'Upright torso', 'Full depth'],
 ARRAY['Leaning forward', 'Knee caving', 'Too narrow stance'],
 ARRAY['quads', 'glutes'], ARRAY['hamstrings', 'core'], ARRAY['dumbbells', 'bench'],
 'intermediate', 'squat', 'strength', 'https://v2.exercisedb.io/image/FqKpNxLe0TW8rd', false, false, true),

('Walking Lunge', 'walking-lunge', 'Dynamic single leg exercise.',
 ARRAY['Step forward into lunge', 'Lower until rear knee near floor', 'Step through to next lunge', 'Keep torso upright'],
 ARRAY['Knees track toes', 'Upright posture', 'Controlled steps'],
 ARRAY['Knee caving', 'Leaning forward', 'Too long steps'],
 ARRAY['quads', 'glutes'], ARRAY['hamstrings', 'core'], ARRAY['dumbbells', 'bodyweight'],
 'beginner', 'squat', 'strength', 'https://v2.exercisedb.io/image/GqKpNxLe0TW8rd', false, false, true),

('Reverse Lunge', 'reverse-lunge', 'Knee-friendly lunge variation.',
 ARRAY['Step backward into lunge', 'Lower until rear knee near floor', 'Drive up through front heel', 'Return to start'],
 ARRAY['Stay upright', 'Front knee stable', 'Control descent'],
 ARRAY['Knee caving', 'Rushing', 'Balance issues'],
 ARRAY['quads', 'glutes'], ARRAY['hamstrings', 'core'], ARRAY['dumbbells', 'bodyweight'],
 'beginner', 'squat', 'strength', 'https://v2.exercisedb.io/image/HqKpNxLe0TW8rd', false, false, true),

('Leg Extension', 'leg-extension', 'Quad isolation exercise.',
 ARRAY['Sit in leg extension machine', 'Adjust pad to ankles', 'Extend legs straight', 'Lower with control'],
 ARRAY['Full extension', 'Squeeze quads at top', 'Control negative'],
 ARRAY['Swinging weight', 'Partial range', 'Too heavy'],
 ARRAY['quads'], ARRAY[]::text[], ARRAY['leg extension machine'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/IqKpNxLe0TW8rd', true, true, true),

('Step Up', 'step-up', 'Functional single leg exercise.',
 ARRAY['Stand facing bench or box', 'Step up driving through heel', 'Bring other leg up', 'Step down with control'],
 ARRAY['Drive through stepping leg', 'Dont push off back foot', 'Control descent'],
 ARRAY['Pushing off floor', 'Box too high', 'Rushing'],
 ARRAY['quads', 'glutes'], ARRAY['hamstrings', 'core'], ARRAY['dumbbells', 'bench', 'box'],
 'beginner', 'squat', 'strength', 'https://v2.exercisedb.io/image/JqKpNxLe0TW8rd', false, false, true),

('Sissy Squat', 'sissy-squat', 'Advanced quad isolation movement.',
 ARRAY['Stand holding support', 'Lean back while bending knees', 'Lower until full quad stretch', 'Return to start'],
 ARRAY['Keep hips extended', 'Go deep for stretch', 'Control movement'],
 ARRAY['Bending at hips', 'Not deep enough', 'No support'],
 ARRAY['quads'], ARRAY[]::text[], ARRAY['bodyweight', 'sissy squat machine'],
 'advanced', 'squat', 'strength', 'https://v2.exercisedb.io/image/KqKpNxLe0TW8rd', false, true, true),

-- Hamstring Dominant
('Romanian Deadlift', 'romanian-deadlift', 'Hip hinge for hamstring and glute development.',
 ARRAY['Hold bar at thighs', 'Hinge at hips pushing butt back', 'Lower bar along legs until hamstring stretch', 'Return to standing'],
 ARRAY['Slight knee bend', 'Back stays flat', 'Feel hamstring stretch'],
 ARRAY['Rounding back', 'Bending knees too much', 'Not hinging'],
 ARRAY['hamstrings', 'glutes'], ARRAY['lower back'], ARRAY['barbell', 'dumbbells'],
 'intermediate', 'hinge', 'strength', 'https://v2.exercisedb.io/image/LqKpNxLe0TW8rd', false, true, true),

('Stiff Leg Deadlift', 'stiff-leg-deadlift', 'Straight leg variation targeting hamstrings.',
 ARRAY['Hold bar at thighs', 'Minimal knee bend', 'Hinge and lower bar', 'Return when max stretch reached'],
 ARRAY['Legs stay stiff', 'Deep stretch', 'Back flat'],
 ARRAY['Too much knee bend', 'Rounding back', 'Going too heavy'],
 ARRAY['hamstrings'], ARRAY['lower back', 'glutes'], ARRAY['barbell'],
 'intermediate', 'hinge', 'strength', 'https://v2.exercisedb.io/image/MqKpNxLe0TW8rd', false, true, true),

('Single Leg RDL', 'single-leg-rdl', 'Unilateral hip hinge for balance and strength.',
 ARRAY['Stand on one leg', 'Hinge forward extending other leg back', 'Lower until hamstring stretch', 'Return to standing'],
 ARRAY['Hips stay square', 'Balance throughout', 'Control the motion'],
 ARRAY['Rotating hips', 'Rushing', 'Not deep enough'],
 ARRAY['hamstrings', 'glutes'], ARRAY['core', 'lower back'], ARRAY['dumbbell', 'kettlebell'],
 'intermediate', 'hinge', 'strength', 'https://v2.exercisedb.io/image/NqKpNxLe0TW8rd', false, false, true),

('Lying Leg Curl', 'lying-leg-curl', 'Machine hamstring isolation.',
 ARRAY['Lie face down on machine', 'Adjust pad to ankles', 'Curl legs up', 'Lower with control'],
 ARRAY['Full range of motion', 'Squeeze at top', 'Control negative'],
 ARRAY['Hips rising', 'Swinging weight', 'Partial reps'],
 ARRAY['hamstrings'], ARRAY[]::text[], ARRAY['leg curl machine'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/OqKpNxLe0TW8rd', true, true, true),

('Seated Leg Curl', 'seated-leg-curl', 'Alternative hamstring curl position.',
 ARRAY['Sit in machine with pad on ankles', 'Curl legs under seat', 'Squeeze at bottom', 'Return with control'],
 ARRAY['Keep back against pad', 'Full range', 'Squeeze at contraction'],
 ARRAY['Leaning forward', 'Partial range', 'Swinging'],
 ARRAY['hamstrings'], ARRAY[]::text[], ARRAY['seated leg curl machine'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/PqKpNxLe0TW8rd', true, true, true),

('Nordic Hamstring Curl', 'nordic-hamstring-curl', 'Advanced eccentric hamstring exercise.',
 ARRAY['Kneel with ankles secured', 'Lower body forward with control', 'Catch yourself at bottom', 'Use arms to help push back up'],
 ARRAY['Control the descent', 'Hamstrings fight gravity', 'Smooth movement'],
 ARRAY['Falling too fast', 'Bending at hips', 'No control'],
 ARRAY['hamstrings'], ARRAY['glutes'], ARRAY['partner', 'nordic bench'],
 'advanced', 'isolation', 'strength', 'https://v2.exercisedb.io/image/QqKpNxLe0TW8rd', false, true, true),

('Glute Ham Raise', 'glute-ham-raise', 'Advanced posterior chain exercise.',
 ARRAY['Set up on GHD with hips on pad', 'Lower torso toward floor', 'Curl up using hamstrings', 'Extend at top'],
 ARRAY['Hamstrings do the work', 'Full range', 'Control throughout'],
 ARRAY['Using momentum', 'Too much hip extension', 'Cutting range'],
 ARRAY['hamstrings', 'glutes'], ARRAY['lower back'], ARRAY['GHD machine'],
 'advanced', 'hinge', 'strength', 'https://v2.exercisedb.io/image/RqKpNxLe0TW8rd', true, true, true),

-- Glute Focused
('Hip Thrust', 'hip-thrust', 'The best exercise for glute development.',
 ARRAY['Upper back on bench', 'Barbell over hips', 'Drive hips up squeezing glutes', 'Lower with control'],
 ARRAY['Squeeze hard at top', 'Full hip extension', 'Dont hyperextend'],
 ARRAY['Hyperextending lower back', 'Not driving high enough', 'Too fast'],
 ARRAY['glutes'], ARRAY['hamstrings'], ARRAY['barbell', 'bench'],
 'intermediate', 'hinge', 'strength', 'https://v2.exercisedb.io/image/SqKpNxLe0TW8rd', false, true, true),

('Glute Bridge', 'glute-bridge', 'Beginner-friendly glute exercise.',
 ARRAY['Lie on back with knees bent', 'Drive hips up squeezing glutes', 'Hold at top briefly', 'Lower with control'],
 ARRAY['Squeeze glutes hard', 'Full extension', 'Dont arch lower back'],
 ARRAY['Hyperextending', 'Not squeezing', 'Using hamstrings only'],
 ARRAY['glutes'], ARRAY['hamstrings', 'core'], ARRAY['bodyweight', 'barbell'],
 'beginner', 'hinge', 'strength', 'https://v2.exercisedb.io/image/TqKpNxLe0TW8rd', false, true, true),

('Cable Kickback', 'cable-kickback', 'Glute isolation with constant tension.',
 ARRAY['Attach ankle cuff to low cable', 'Face cable machine', 'Kick leg back squeezing glute', 'Return with control'],
 ARRAY['Squeeze at top', 'Minimal lower back arch', 'Control throughout'],
 ARRAY['Arching lower back', 'Swinging leg', 'Too much weight'],
 ARRAY['glutes'], ARRAY['hamstrings'], ARRAY['cable machine', 'ankle cuff'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/UqKpNxLe0TW8rd', false, false, true),

('Cable Pull Through', 'cable-pull-through', 'Hip hinge with cable for glute activation.',
 ARRAY['Face away from low cable', 'Hold rope between legs', 'Hinge at hips', 'Drive hips forward squeezing glutes'],
 ARRAY['Hip hinge motion', 'Squeeze at top', 'Feel glutes working'],
 ARRAY['Squatting instead of hinging', 'Not finishing with glutes', 'Too heavy'],
 ARRAY['glutes', 'hamstrings'], ARRAY['lower back'], ARRAY['cable machine', 'rope'],
 'beginner', 'hinge', 'strength', 'https://v2.exercisedb.io/image/VqKpNxLe0TW8rd', false, true, true),

('Sumo Deadlift', 'sumo-deadlift', 'Wide stance deadlift for glutes and inner thighs.',
 ARRAY['Wide stance with toes out', 'Grip bar inside legs', 'Push floor away keeping back flat', 'Stand tall squeezing glutes'],
 ARRAY['Knees track toes', 'Hips and shoulders rise together', 'Lockout with glutes'],
 ARRAY['Knees caving', 'Rounding back', 'Not using leg drive'],
 ARRAY['glutes', 'adductors'], ARRAY['quads', 'hamstrings', 'lower back'], ARRAY['barbell'],
 'intermediate', 'hinge', 'strength', 'https://v2.exercisedb.io/image/WqKpNxLe0TW8rd', false, true, true),

('Frog Pump', 'frog-pump', 'Unique glute activation exercise.',
 ARRAY['Lie on back with soles together', 'Knees fall outward', 'Drive hips up', 'Squeeze glutes at top'],
 ARRAY['High reps', 'Constant tension', 'Squeeze hard'],
 ARRAY['Not enough range', 'Rushing', 'Not squeezing'],
 ARRAY['glutes'], ARRAY[]::text[], ARRAY['bodyweight', 'band'],
 'beginner', 'hinge', 'strength', 'https://v2.exercisedb.io/image/XqKpNxLe0TW8rd', false, true, true),

-- Calf Exercises
('Standing Calf Raise', 'standing-calf-raise', 'Classic calf builder for gastrocnemius.',
 ARRAY['Stand on calf raise platform', 'Lower heels below platform', 'Raise up on toes', 'Squeeze at top'],
 ARRAY['Full stretch at bottom', 'High on toes at top', 'Control throughout'],
 ARRAY['Bouncing', 'Partial range', 'Bending knees'],
 ARRAY['gastrocnemius'], ARRAY['soleus'], ARRAY['calf raise machine', 'smith machine'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/YqKpNxLe0TW8rd', true, true, true),

('Seated Calf Raise', 'seated-calf-raise', 'Target soleus muscle.',
 ARRAY['Sit with pad on knees', 'Lower heels for stretch', 'Raise on toes', 'Squeeze at top'],
 ARRAY['Full range of motion', 'Squeeze at top', 'Slow negatives'],
 ARRAY['Bouncing', 'Not going deep', 'Too fast'],
 ARRAY['soleus'], ARRAY['gastrocnemius'], ARRAY['seated calf raise machine'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/ZqKpNxLe0TW8rd', true, true, true),

('Donkey Calf Raise', 'donkey-calf-raise', 'Stretched position calf exercise.',
 ARRAY['Bend over at waist', 'Weight on lower back or partner', 'Lower heels for stretch', 'Raise on toes'],
 ARRAY['Deep stretch', 'Full extension', 'Control movement'],
 ARRAY['Not enough stretch', 'Rushing reps', 'Poor form'],
 ARRAY['gastrocnemius'], ARRAY['soleus'], ARRAY['donkey calf machine', 'partner'],
 'intermediate', 'isolation', 'strength', 'https://v2.exercisedb.io/image/0qKpNxLe0TW8rd', true, true, true),

('Single Leg Calf Raise', 'single-leg-calf-raise', 'Unilateral calf work.',
 ARRAY['Stand on one leg on edge of step', 'Lower heel for stretch', 'Raise up on toes', 'Squeeze at top'],
 ARRAY['Full range', 'Balance throughout', 'Squeeze at top'],
 ARRAY['Rushing', 'Partial range', 'Using momentum'],
 ARRAY['gastrocnemius', 'soleus'], ARRAY[]::text[], ARRAY['step', 'dumbbell'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/1qKpNxLe0TW8rd', false, false, true),

-- Compound Movements
('Barbell Deadlift', 'barbell-deadlift', 'Total body strength builder.',
 ARRAY['Stand with feet hip width under bar', 'Grip bar outside legs', 'Drive through floor', 'Stand tall squeezing glutes'],
 ARRAY['Bar close to body', 'Back flat throughout', 'Lockout at top'],
 ARRAY['Rounding back', 'Bar drifting forward', 'Jerking weight'],
 ARRAY['hamstrings', 'glutes', 'lower back'], ARRAY['quads', 'core', 'traps'], ARRAY['barbell'],
 'intermediate', 'hinge', 'strength', 'https://v2.exercisedb.io/image/2qKpNxLe0TW8rd', false, true, true),

('Trap Bar Deadlift', 'trap-bar-deadlift', 'Neutral grip deadlift easier on lower back.',
 ARRAY['Stand inside trap bar', 'Grip handles at sides', 'Drive through floor', 'Stand tall'],
 ARRAY['Neutral grip', 'Drive through heels', 'Keep torso upright'],
 ARRAY['Rounding back', 'Starting too low', 'Not using legs enough'],
 ARRAY['quads', 'hamstrings', 'glutes'], ARRAY['lower back', 'traps'], ARRAY['trap bar'],
 'beginner', 'hinge', 'strength', 'https://v2.exercisedb.io/image/3qKpNxLe0TW8rd', false, true, true),

('Kettlebell Swing', 'kettlebell-swing', 'Explosive hip hinge for power and conditioning.',
 ARRAY['Hike kettlebell between legs', 'Drive hips forward explosively', 'Swing to chest height', 'Let gravity bring it back'],
 ARRAY['Hip hinge not squat', 'Snap hips at top', 'Arms are just along for the ride'],
 ARRAY['Squatting instead of hinging', 'Using arms to lift', 'Not snapping hips'],
 ARRAY['glutes', 'hamstrings'], ARRAY['core', 'shoulders'], ARRAY['kettlebell'],
 'beginner', 'hinge', 'strength', 'https://v2.exercisedb.io/image/4qKpNxLe0TW8rd', false, true, true),

('Box Jump', 'box-jump', 'Explosive plyometric for lower body power.',
 ARRAY['Stand facing box', 'Swing arms and jump onto box', 'Land softly with bent knees', 'Step down and repeat'],
 ARRAY['Soft landing', 'Full hip extension at top', 'Controlled step down'],
 ARRAY['Landing too hard', 'Jumping off box', 'Box too high'],
 ARRAY['quads', 'glutes'], ARRAY['calves', 'hamstrings'], ARRAY['box', 'plyo box'],
 'intermediate', 'squat', 'strength', 'https://v2.exercisedb.io/image/5qKpNxLe0TW8rd', false, true, true),

('Jump Squat', 'jump-squat', 'Explosive squat variation.',
 ARRAY['Squat down', 'Explode up jumping', 'Land softly', 'Immediately repeat'],
 ARRAY['Soft landing', 'Full depth squat', 'Explosive jump'],
 ARRAY['Shallow squat', 'Hard landing', 'Losing form fatigue'],
 ARRAY['quads', 'glutes'], ARRAY['calves', 'hamstrings'], ARRAY['bodyweight'],
 'intermediate', 'squat', 'strength', 'https://v2.exercisedb.io/image/6qKpNxLe0TW8rd', false, true, true),

('Wall Sit', 'wall-sit', 'Isometric quad endurance exercise.',
 ARRAY['Back against wall', 'Slide down until thighs parallel', 'Hold position', 'Breathe steadily'],
 ARRAY['Thighs parallel to floor', 'Back flat on wall', 'Hold as long as possible'],
 ARRAY['Not going deep enough', 'Leaning forward', 'Holding breath'],
 ARRAY['quads'], ARRAY['glutes'], ARRAY['wall'],
 'beginner', 'squat', 'strength', 'https://v2.exercisedb.io/image/7qKpNxLe0TW8rd', false, true, true),

('Bodyweight Squat', 'bodyweight-squat', 'Fundamental squat pattern.',
 ARRAY['Stand with feet shoulder width', 'Squat down keeping chest up', 'Go as deep as mobility allows', 'Stand back up'],
 ARRAY['Chest up', 'Knees track toes', 'Full depth'],
 ARRAY['Heels rising', 'Knees caving', 'Rounding back'],
 ARRAY['quads', 'glutes'], ARRAY['hamstrings', 'core'], ARRAY['bodyweight'],
 'beginner', 'squat', 'strength', 'https://v2.exercisedb.io/image/8qKpNxLe0TW8rd', false, true, true),

('Pistol Squat', 'pistol-squat', 'Advanced single leg squat.',
 ARRAY['Stand on one leg', 'Squat down extending other leg forward', 'Go as low as possible', 'Drive back up'],
 ARRAY['Keep extended leg straight', 'Control descent', 'Balance throughout'],
 ARRAY['Falling backward', 'Not going deep', 'Knee caving'],
 ARRAY['quads', 'glutes'], ARRAY['hamstrings', 'core'], ARRAY['bodyweight'],
 'advanced', 'squat', 'strength', 'https://v2.exercisedb.io/image/9qKpNxLe0TW8rd', false, false, true),

('Smith Machine Squat', 'smith-machine-squat', 'Guided squat for safety.',
 ARRAY['Position bar on upper back', 'Feet slightly forward', 'Squat down', 'Drive back up'],
 ARRAY['Full depth', 'Control throughout', 'Feet forward for quads'],
 ARRAY['Feet too far forward', 'Partial reps', 'Relying too much on machine'],
 ARRAY['quads', 'glutes'], ARRAY['hamstrings'], ARRAY['smith machine'],
 'beginner', 'squat', 'strength', 'https://v2.exercisedb.io/image/aqKpNxLe0TW8rd', true, true, true),

('Hip Adduction Machine', 'hip-adduction-machine', 'Inner thigh targeting.',
 ARRAY['Sit with legs against pads', 'Squeeze legs together', 'Control return', 'Repeat'],
 ARRAY['Squeeze at contraction', 'Full range', 'Control negative'],
 ARRAY['Going too fast', 'Partial range', 'Too heavy'],
 ARRAY['adductors'], ARRAY[]::text[], ARRAY['adduction machine'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/bqKpNxLe0TW8rd', true, true, true),

('Hip Abduction Machine', 'hip-abduction-machine', 'Outer thigh and glute targeting.',
 ARRAY['Sit with legs inside pads', 'Push legs apart', 'Control return', 'Repeat'],
 ARRAY['Squeeze at end', 'Full range', 'Control negative'],
 ARRAY['Going too fast', 'Partial range', 'Too heavy'],
 ARRAY['glute medius', 'abductors'], ARRAY[]::text[], ARRAY['abduction machine'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/cqKpNxLe0TW8rd', true, true, true);

-- ============================================
-- CORE EXERCISES (25)
-- ============================================

INSERT INTO exercises (name, slug, description, instructions, cues, common_mistakes, primary_muscles, secondary_muscles, equipment_names, difficulty, movement_pattern, exercise_type, video_url, is_machine, is_bilateral, is_published)
VALUES
('Plank', 'plank', 'Foundational core stability exercise.',
 ARRAY['Forearms on floor elbows under shoulders', 'Body in straight line', 'Hold position', 'Breathe steadily'],
 ARRAY['Squeeze everything tight', 'Dont let hips sag', 'Neutral spine'],
 ARRAY['Hips sagging', 'Hips too high', 'Holding breath'],
 ARRAY['core', 'transverse abdominis'], ARRAY['shoulders', 'glutes'], ARRAY['bodyweight'],
 'beginner', 'core', 'strength', 'https://v2.exercisedb.io/image/dqKpNxLe0TW8rd', false, true, true),

('Side Plank', 'side-plank', 'Oblique and lateral core stability.',
 ARRAY['Lie on side with forearm on floor', 'Lift hips creating straight line', 'Hold position', 'Repeat other side'],
 ARRAY['Hips stacked', 'Body straight', 'Engage obliques'],
 ARRAY['Hips dropping', 'Rotating forward', 'Not breathing'],
 ARRAY['obliques', 'core'], ARRAY['glutes', 'shoulders'], ARRAY['bodyweight'],
 'intermediate', 'core', 'strength', 'https://v2.exercisedb.io/image/eqKpNxLe0TW8rd', false, false, true),

('Dead Bug', 'dead-bug', 'Anti-extension core exercise.',
 ARRAY['Lie on back with arms up and knees at 90 degrees', 'Lower opposite arm and leg', 'Keep lower back pressed to floor', 'Return and repeat other side'],
 ARRAY['Lower back stays flat', 'Controlled movement', 'Exhale on extension'],
 ARRAY['Lower back arching', 'Going too fast', 'Not coordinating'],
 ARRAY['core', 'transverse abdominis'], ARRAY['hip flexors'], ARRAY['bodyweight'],
 'beginner', 'core', 'strength', 'https://v2.exercisedb.io/image/fqKpNxLe0TW8rd', false, false, true),

('Bird Dog', 'bird-dog', 'Core stability and balance exercise.',
 ARRAY['Start on hands and knees', 'Extend opposite arm and leg', 'Hold briefly', 'Return and repeat other side'],
 ARRAY['Keep back flat', 'Extend fully', 'Minimal movement in torso'],
 ARRAY['Rotating hips', 'Arching back', 'Rushing'],
 ARRAY['core', 'erector spinae'], ARRAY['glutes', 'shoulders'], ARRAY['bodyweight'],
 'beginner', 'core', 'strength', 'https://v2.exercisedb.io/image/gqKpNxLe0TW8rd', false, false, true),

('Crunch', 'crunch', 'Basic upper ab exercise.',
 ARRAY['Lie on back with knees bent', 'Hands behind head or across chest', 'Curl shoulders off floor', 'Lower with control'],
 ARRAY['Exhale on the way up', 'Dont pull on neck', 'Feel abs working'],
 ARRAY['Pulling on neck', 'Using momentum', 'Not controlling descent'],
 ARRAY['rectus abdominis'], ARRAY[]::text[], ARRAY['bodyweight'],
 'beginner', 'core', 'strength', 'https://v2.exercisedb.io/image/hqKpNxLe0TW8rd', false, true, true),

('Bicycle Crunch', 'bicycle-crunch', 'Dynamic ab exercise hitting obliques.',
 ARRAY['Lie on back with hands behind head', 'Bring knee to opposite elbow', 'Rotate torso', 'Alternate sides continuously'],
 ARRAY['Control the motion', 'Twist from core', 'Dont pull on neck'],
 ARRAY['Going too fast', 'Pulling on neck', 'Not fully rotating'],
 ARRAY['obliques', 'rectus abdominis'], ARRAY['hip flexors'], ARRAY['bodyweight'],
 'beginner', 'core', 'strength', 'https://v2.exercisedb.io/image/iqKpNxLe0TW8rd', false, false, true),

('Reverse Crunch', 'reverse-crunch', 'Lower ab focused crunch.',
 ARRAY['Lie on back with knees bent', 'Curl hips off floor', 'Bring knees toward chest', 'Lower with control'],
 ARRAY['Curl hips not swing legs', 'Control descent', 'Exhale on lift'],
 ARRAY['Using momentum', 'Swinging legs', 'Not curling hips'],
 ARRAY['lower abs', 'rectus abdominis'], ARRAY['hip flexors'], ARRAY['bodyweight'],
 'beginner', 'core', 'strength', 'https://v2.exercisedb.io/image/jqKpNxLe0TW8rd', false, true, true),

('Hanging Leg Raise', 'hanging-leg-raise', 'Advanced lower ab exercise.',
 ARRAY['Hang from pull-up bar', 'Raise legs to parallel or higher', 'Lower with control', 'Minimize swinging'],
 ARRAY['Control the movement', 'Go high for more ab activation', 'Dont swing'],
 ARRAY['Swinging', 'Using momentum', 'Not raising high enough'],
 ARRAY['lower abs', 'hip flexors'], ARRAY['core', 'forearms'], ARRAY['pull-up bar'],
 'advanced', 'core', 'strength', 'https://v2.exercisedb.io/image/kqKpNxLe0TW8rd', false, true, true),

('Hanging Knee Raise', 'hanging-knee-raise', 'Intermediate hanging ab exercise.',
 ARRAY['Hang from pull-up bar', 'Raise knees to chest', 'Lower with control', 'Minimize swinging'],
 ARRAY['Curl pelvis up', 'Control descent', 'Engage core throughout'],
 ARRAY['Swinging', 'Just raising legs not curling', 'Too fast'],
 ARRAY['lower abs', 'hip flexors'], ARRAY['core', 'forearms'], ARRAY['pull-up bar'],
 'intermediate', 'core', 'strength', 'https://v2.exercisedb.io/image/lqKpNxLe0TW8rd', false, true, true),

('Cable Crunch', 'cable-crunch', 'Weighted ab crunch for progressive overload.',
 ARRAY['Kneel facing cable with rope', 'Hold rope at head', 'Crunch down toward floor', 'Return with control'],
 ARRAY['Curl from abs not hips', 'Squeeze at bottom', 'Control negative'],
 ARRAY['Sitting back on heels', 'Using too much weight', 'Hip hinging'],
 ARRAY['rectus abdominis'], ARRAY['hip flexors'], ARRAY['cable machine', 'rope'],
 'intermediate', 'core', 'strength', 'https://v2.exercisedb.io/image/mqKpNxLe0TW8rd', false, true, true),

('Wood Chop', 'wood-chop', 'Rotational core exercise.',
 ARRAY['Set cable high or use medicine ball', 'Pull diagonally across body', 'Rotate through core', 'Return with control'],
 ARRAY['Rotate from core', 'Keep arms relatively straight', 'Control the motion'],
 ARRAY['All arms no core', 'Too heavy', 'Not rotating enough'],
 ARRAY['obliques', 'core'], ARRAY['shoulders', 'hips'], ARRAY['cable machine', 'medicine ball'],
 'intermediate', 'core', 'strength', 'https://v2.exercisedb.io/image/nqKpNxLe0TW8rd', false, false, true),

('Russian Twist', 'russian-twist', 'Rotational exercise for obliques.',
 ARRAY['Sit with knees bent feet off floor', 'Lean back slightly', 'Rotate side to side', 'Touch weight to floor each side'],
 ARRAY['Rotate from core', 'Keep feet up', 'Control movement'],
 ARRAY['Just moving arms', 'Feet on floor', 'Going too fast'],
 ARRAY['obliques'], ARRAY['hip flexors'], ARRAY['medicine ball', 'dumbbell', 'plate'],
 'beginner', 'core', 'strength', 'https://v2.exercisedb.io/image/oqKpNxLe0TW8rd', false, false, true),

('Pallof Press', 'pallof-press', 'Anti-rotation core stability.',
 ARRAY['Stand sideways to cable', 'Hold handle at chest', 'Press straight out', 'Return to chest resist rotation'],
 ARRAY['Resist rotation', 'Press from core', 'Hold at extension'],
 ARRAY['Rotating', 'Using arms only', 'Too light weight'],
 ARRAY['core', 'obliques'], ARRAY['shoulders'], ARRAY['cable machine', 'band'],
 'intermediate', 'core', 'strength', 'https://v2.exercisedb.io/image/pqKpNxLe0TW8rd', false, false, true),

('Ab Wheel Rollout', 'ab-wheel-rollout', 'Advanced core extension exercise.',
 ARRAY['Kneel with hands on ab wheel', 'Roll forward extending body', 'Keep core tight go as far as possible', 'Roll back using abs'],
 ARRAY['Dont let hips sag', 'Core tight throughout', 'Control the motion'],
 ARRAY['Hips sagging', 'Going too far losing form', 'Using too much hip'],
 ARRAY['rectus abdominis', 'core'], ARRAY['lats', 'hip flexors'], ARRAY['ab wheel'],
 'advanced', 'core', 'strength', 'https://v2.exercisedb.io/image/qqKpNxLe0TW8rd', false, true, true),

('Mountain Climber', 'mountain-climber', 'Dynamic core and cardio exercise.',
 ARRAY['Start in push-up position', 'Drive one knee to chest', 'Switch legs quickly', 'Maintain push-up position'],
 ARRAY['Keep hips down', 'Drive knees in', 'Steady pace'],
 ARRAY['Hips rising', 'Bouncing', 'Losing form as fatigued'],
 ARRAY['core', 'hip flexors'], ARRAY['shoulders', 'quads'], ARRAY['bodyweight'],
 'beginner', 'core', 'cardio', 'https://v2.exercisedb.io/image/rqKpNxLe0TW8rd', false, false, true),

('V-Up', 'v-up', 'Advanced full ab exercise.',
 ARRAY['Lie flat on back', 'Simultaneously raise legs and torso', 'Touch toes at top', 'Lower with control'],
 ARRAY['Meet in the middle', 'Keep legs straight', 'Control descent'],
 ARRAY['Bending knees', 'Using momentum', 'Not meeting at top'],
 ARRAY['rectus abdominis', 'hip flexors'], ARRAY[]::text[], ARRAY['bodyweight'],
 'advanced', 'core', 'strength', 'https://v2.exercisedb.io/image/sqKpNxLe0TW8rd', false, true, true),

('Toe Touch', 'toe-touch', 'Upper ab crunch variation.',
 ARRAY['Lie on back with legs vertical', 'Reach hands toward toes', 'Lift shoulders off floor', 'Lower with control'],
 ARRAY['Keep legs vertical', 'Reach for toes', 'Exhale on crunch'],
 ARRAY['Legs falling', 'Using momentum', 'Not reaching high enough'],
 ARRAY['upper abs', 'rectus abdominis'], ARRAY[]::text[], ARRAY['bodyweight'],
 'beginner', 'core', 'strength', 'https://v2.exercisedb.io/image/tqKpNxLe0TW8rd', false, true, true),

('L-Sit', 'l-sit', 'Advanced isometric core hold.',
 ARRAY['Sit with legs straight', 'Place hands beside hips', 'Lift body off floor legs extended', 'Hold position'],
 ARRAY['Keep legs straight', 'Press through hands', 'Breathe steadily'],
 ARRAY['Bending knees', 'Not lifting high enough', 'Giving up too early'],
 ARRAY['hip flexors', 'core'], ARRAY['triceps', 'shoulders'], ARRAY['parallettes', 'dip bars'],
 'advanced', 'core', 'strength', 'https://v2.exercisedb.io/image/uqKpNxLe0TW8rd', false, true, true),

('Dragon Flag', 'dragon-flag', 'Elite level core exercise.',
 ARRAY['Lie on bench holding behind head', 'Raise entire body up', 'Lower slowly as one unit', 'Dont let lower back touch'],
 ARRAY['Body stays straight', 'Extremely slow negative', 'Full control'],
 ARRAY['Bending at hips', 'Going too fast', 'Lower back touching'],
 ARRAY['core', 'rectus abdominis'], ARRAY['hip flexors', 'lats'], ARRAY['bench'],
 'advanced', 'core', 'strength', 'https://v2.exercisedb.io/image/vqKpNxLe0TW8rd', false, true, true),

('Flutter Kicks', 'flutter-kicks', 'Lower ab endurance exercise.',
 ARRAY['Lie on back with legs straight', 'Lift legs slightly off floor', 'Alternate kicking up and down', 'Keep lower back pressed down'],
 ARRAY['Lower back stays flat', 'Small controlled kicks', 'Breathe steadily'],
 ARRAY['Lower back arching', 'Legs too high', 'Going too fast'],
 ARRAY['lower abs', 'hip flexors'], ARRAY[]::text[], ARRAY['bodyweight'],
 'beginner', 'core', 'strength', 'https://v2.exercisedb.io/image/wqKpNxLe0TW8rd', false, false, true),

('Leg Raise', 'leg-raise', 'Lying lower ab exercise.',
 ARRAY['Lie on back with legs straight', 'Raise legs to vertical', 'Lower with control', 'Keep lower back pressed down'],
 ARRAY['Lower back flat throughout', 'Control the descent', 'Go all the way up'],
 ARRAY['Lower back arching', 'Using momentum', 'Not going full range'],
 ARRAY['lower abs', 'hip flexors'], ARRAY[]::text[], ARRAY['bodyweight'],
 'intermediate', 'core', 'strength', 'https://v2.exercisedb.io/image/xqKpNxLe0TW8rd', false, true, true),

('Sit-Up', 'sit-up', 'Classic ab exercise.',
 ARRAY['Lie on back with knees bent', 'Feet anchored or not', 'Sit all the way up', 'Lower with control'],
 ARRAY['Come all the way up', 'Dont pull on neck', 'Control descent'],
 ARRAY['Pulling on neck', 'Using momentum', 'Hip flexor dominant'],
 ARRAY['rectus abdominis', 'hip flexors'], ARRAY[]::text[], ARRAY['bodyweight'],
 'beginner', 'core', 'strength', 'https://v2.exercisedb.io/image/yqKpNxLe0TW8rd', false, true, true),

('Hollow Body Hold', 'hollow-body-hold', 'Gymnastics core stability position.',
 ARRAY['Lie on back', 'Lift legs and shoulders off floor', 'Arms overhead or at sides', 'Hold position pressing lower back down'],
 ARRAY['Lower back stays flat', 'Create banana shape', 'Breathe throughout'],
 ARRAY['Lower back arching', 'Legs too high', 'Giving up early'],
 ARRAY['core', 'rectus abdominis'], ARRAY['hip flexors'], ARRAY['bodyweight'],
 'intermediate', 'core', 'strength', 'https://v2.exercisedb.io/image/zqKpNxLe0TW8rd', false, true, true),

('Machine Crunch', 'machine-crunch', 'Weighted ab crunch on machine.',
 ARRAY['Sit in ab machine', 'Grip handles', 'Crunch forward', 'Return with control'],
 ARRAY['Curl from abs', 'Squeeze at contraction', 'Control negative'],
 ARRAY['Using too much weight', 'Partial range', 'Hip hinging'],
 ARRAY['rectus abdominis'], ARRAY[]::text[], ARRAY['ab machine'],
 'beginner', 'core', 'strength', 'https://v2.exercisedb.io/image/0rKpNxLe0TW8rd', true, true, true),

('Decline Sit-Up', 'decline-sit-up', 'Increased resistance sit-up.',
 ARRAY['Lie on decline bench feet hooked', 'Hands across chest or behind head', 'Sit up fully', 'Lower with control'],
 ARRAY['Full range of motion', 'Control the descent', 'Dont use momentum'],
 ARRAY['Using momentum', 'Coming up too fast', 'Pulling on neck'],
 ARRAY['rectus abdominis', 'hip flexors'], ARRAY[]::text[], ARRAY['decline bench'],
 'intermediate', 'core', 'strength', 'https://v2.exercisedb.io/image/1rKpNxLe0TW8rd', false, true, true);

