-- Migration 012: Complete Exercise Library Part 3
-- Compound Movements, Functional, Olympic, Warmup/Mobility (50+ exercises)

-- ============================================
-- COMPOUND & OLYMPIC LIFTS (20)
-- ============================================

INSERT INTO exercises (name, slug, description, instructions, cues, common_mistakes, primary_muscles, secondary_muscles, equipment_names, difficulty, movement_pattern, exercise_type, video_url, is_machine, is_bilateral, is_published)
VALUES
('Clean and Press', 'clean-and-press', 'Full body power and strength movement.',
 ARRAY['Start with bar on floor', 'Clean bar to shoulders explosively', 'Press overhead', 'Lower to shoulders then floor'],
 ARRAY['Triple extension on clean', 'Full lockout on press', 'Control descent'],
 ARRAY['Not using legs', 'Pressing before settling', 'Poor rack position'],
 ARRAY['total body', 'quads', 'shoulders'], ARRAY['glutes', 'core', 'traps'], ARRAY['barbell'],
 'advanced', 'push', 'strength', 'https://v2.exercisedb.io/image/2rKpNxLe0TW8rd', false, true, true),

('Power Clean', 'power-clean', 'Explosive Olympic lift for power development.',
 ARRAY['Bar on floor hip width grip', 'Drive through floor explosively', 'Triple extend and shrug', 'Catch in power position'],
 ARRAY['Keep bar close', 'Explode at hips', 'Fast elbows'],
 ARRAY['Early arm pull', 'Bar swinging away', 'Not extending fully'],
 ARRAY['hamstrings', 'glutes', 'traps'], ARRAY['quads', 'shoulders', 'core'], ARRAY['barbell'],
 'advanced', 'hinge', 'strength', 'https://v2.exercisedb.io/image/3rKpNxLe0TW8rd', false, true, true),

('Hang Clean', 'hang-clean', 'Clean from hang position.',
 ARRAY['Start at hang position', 'Hinge then explosively extend', 'Pull under bar', 'Catch in front rack'],
 ARRAY['Quick hip snap', 'Fast elbows', 'Catch and stand'],
 ARRAY['Not hinging first', 'Slow elbows', 'Not catching deep enough'],
 ARRAY['glutes', 'hamstrings', 'traps'], ARRAY['quads', 'shoulders'], ARRAY['barbell'],
 'advanced', 'hinge', 'strength', 'https://v2.exercisedb.io/image/4rKpNxLe0TW8rd', false, true, true),

('Push Jerk', 'push-jerk', 'Explosive overhead pressing with split or power catch.',
 ARRAY['Bar in front rack', 'Dip and drive explosively', 'Push under bar catching with bent knees', 'Stand to full lockout'],
 ARRAY['Quick dip', 'Aggressive drive', 'Fast catch'],
 ARRAY['Slow dip', 'Not pushing under', 'Pressing instead of pushing under'],
 ARRAY['shoulders', 'quads', 'triceps'], ARRAY['core', 'glutes'], ARRAY['barbell'],
 'advanced', 'push', 'strength', 'https://v2.exercisedb.io/image/5rKpNxLe0TW8rd', false, true, true),

('Thruster', 'thruster', 'Front squat to overhead press combination.',
 ARRAY['Bar in front rack', 'Squat to full depth', 'Drive up pressing overhead', 'Lower bar to rack and repeat'],
 ARRAY['Use leg drive to press', 'Full depth squat', 'Full lockout overhead'],
 ARRAY['Not going deep enough', 'Pressing before standing', 'Poor rack position'],
 ARRAY['quads', 'shoulders'], ARRAY['glutes', 'core', 'triceps'], ARRAY['barbell', 'dumbbells'],
 'intermediate', 'squat', 'strength', 'https://v2.exercisedb.io/image/6rKpNxLe0TW8rd', false, true, true),

('Snatch Grip Deadlift', 'snatch-grip-deadlift', 'Wide grip deadlift for upper back development.',
 ARRAY['Wide snatch grip on bar', 'Set up like conventional deadlift', 'Drive through floor', 'Stand tall'],
 ARRAY['Wide grip', 'Keep back flat', 'Big upper back work'],
 ARRAY['Grip too narrow', 'Rounding back', 'Not using upper back'],
 ARRAY['upper back', 'traps', 'hamstrings'], ARRAY['glutes', 'lats'], ARRAY['barbell'],
 'intermediate', 'hinge', 'strength', 'https://v2.exercisedb.io/image/7rKpNxLe0TW8rd', false, true, true),

('Barbell Complex', 'barbell-complex', 'Continuous series of barbell movements.',
 ARRAY['Perform deadlift clean squat press row', 'No rest between exercises', 'Bar doesnt touch floor until complete', 'Multiple rounds'],
 ARRAY['Smooth transitions', 'Maintain form throughout', 'Pace yourself'],
 ARRAY['Rushing', 'Form breakdown', 'Too heavy'],
 ARRAY['total body'], ARRAY[]::text[], ARRAY['barbell'],
 'advanced', 'push', 'strength', 'https://v2.exercisedb.io/image/8rKpNxLe0TW8rd', false, true, true),

('Farmers Walk', 'farmers-walk', 'Loaded carry for grip and total body strength.',
 ARRAY['Pick up heavy dumbbells or handles', 'Walk with tall posture', 'Maintain grip throughout', 'Set down with control'],
 ARRAY['Shoulders back', 'Chest up', 'Squeeze grip hard'],
 ARRAY['Leaning forward', 'Poor posture', 'Too short distance'],
 ARRAY['forearms', 'traps', 'core'], ARRAY['glutes', 'quads'], ARRAY['dumbbells', 'farmers handles', 'kettlebells'],
 'beginner', 'carry', 'strength', 'https://v2.exercisedb.io/image/9rKpNxLe0TW8rd', false, true, true),

('Suitcase Carry', 'suitcase-carry', 'Single arm carry for anti-lateral flexion.',
 ARRAY['Pick up weight in one hand', 'Walk staying perfectly upright', 'Resist leaning', 'Switch sides'],
 ARRAY['Stay vertical', 'Resist side bend', 'Core engaged'],
 ARRAY['Leaning to side', 'Too light weight', 'Rushing'],
 ARRAY['obliques', 'core'], ARRAY['forearms', 'shoulders'], ARRAY['dumbbell', 'kettlebell'],
 'beginner', 'carry', 'strength', 'https://v2.exercisedb.io/image/arKpNxLe0TW8rd', false, false, true),

('Overhead Carry', 'overhead-carry', 'Loaded carry with weight overhead.',
 ARRAY['Press weight overhead', 'Lock out arm completely', 'Walk maintaining position', 'Switch sides'],
 ARRAY['Arm locked out', 'Core braced', 'Shoulder packed'],
 ARRAY['Arm bending', 'Leaning', 'Going too fast'],
 ARRAY['shoulders', 'core'], ARRAY['triceps', 'traps'], ARRAY['dumbbell', 'kettlebell'],
 'intermediate', 'carry', 'strength', 'https://v2.exercisedb.io/image/brKpNxLe0TW8rd', false, false, true),

('Turkish Get Up', 'turkish-get-up', 'Complex movement from floor to standing with weight overhead.',
 ARRAY['Lie on back with kettlebell pressed up', 'Roll to elbow then hand', 'Bridge and sweep leg through', 'Stand up keeping weight overhead'],
 ARRAY['Eyes on weight', 'Control each position', 'Smooth transitions'],
 ARRAY['Rushing', 'Losing position', 'Weight too heavy'],
 ARRAY['shoulders', 'core', 'total body'], ARRAY['glutes', 'hips'], ARRAY['kettlebell', 'dumbbell'],
 'advanced', 'core', 'strength', 'https://v2.exercisedb.io/image/crKpNxLe0TW8rd', false, false, true),

('Man Maker', 'man-maker', 'Brutal combination of row push-up clean press.',
 ARRAY['Start in push-up position with dumbbells', 'Row each side', 'Perform push-up', 'Jump feet in clean and press'],
 ARRAY['Control rows', 'Explosive clean', 'Full press'],
 ARRAY['Sloppy form', 'Going too heavy', 'Rushing'],
 ARRAY['total body'], ARRAY[]::text[], ARRAY['dumbbells'],
 'advanced', 'push', 'strength', 'https://v2.exercisedb.io/image/drKpNxLe0TW8rd', false, true, true),

('Zercher Squat', 'zercher-squat', 'Squat with bar in elbow crooks.',
 ARRAY['Hold bar in elbow crooks', 'Squat down keeping upright', 'Drive up through heels', 'Keep elbows close'],
 ARRAY['Stay very upright', 'Elbows tight', 'Full depth'],
 ARRAY['Forward lean', 'Bar slipping', 'Elbows flaring'],
 ARRAY['quads', 'core'], ARRAY['glutes', 'upper back'], ARRAY['barbell'],
 'advanced', 'squat', 'strength', 'https://v2.exercisedb.io/image/erKpNxLe0TW8rd', false, true, true),

('Jefferson Deadlift', 'jefferson-deadlift', 'Asymmetrical deadlift variation.',
 ARRAY['Straddle bar with split stance', 'Grip bar one hand front one back', 'Drive up staying balanced', 'Return with control'],
 ARRAY['Resist rotation', 'Even pressure both legs', 'Control descent'],
 ARRAY['Rotating', 'Uneven stance', 'Poor grip'],
 ARRAY['quads', 'glutes', 'hamstrings'], ARRAY['core', 'adductors'], ARRAY['barbell'],
 'advanced', 'hinge', 'strength', 'https://v2.exercisedb.io/image/frKpNxLe0TW8rd', false, false, true),

('Deficit Deadlift', 'deficit-deadlift', 'Deadlift from elevated position for increased ROM.',
 ARRAY['Stand on plates or platform', 'Set up for conventional deadlift', 'Pull from deeper starting position', 'Complete full lockout'],
 ARRAY['Keep back flat', 'Drive through floor', 'Full range of motion'],
 ARRAY['Back rounding', 'Not using deficit', 'Too high deficit'],
 ARRAY['hamstrings', 'glutes', 'lower back'], ARRAY['quads', 'core'], ARRAY['barbell', 'plates'],
 'advanced', 'hinge', 'strength', 'https://v2.exercisedb.io/image/grKpNxLe0TW8rd', false, true, true),

('Pause Squat', 'pause-squat', 'Squat with pause at bottom for strength.',
 ARRAY['Descend into full squat', 'Pause 2-3 seconds at bottom', 'Drive up explosively', 'Complete lockout'],
 ARRAY['Stay tight during pause', 'Explosive drive', 'Maintain position'],
 ARRAY['Short pause', 'Losing tension', 'Bouncing'],
 ARRAY['quads', 'glutes'], ARRAY['core', 'hamstrings'], ARRAY['barbell'],
 'intermediate', 'squat', 'strength', 'https://v2.exercisedb.io/image/hrKpNxLe0TW8rd', false, true, true),

('Anderson Squat', 'anderson-squat', 'Squat from dead stop in power rack.',
 ARRAY['Set safety pins at bottom squat position', 'Start from bottom under bar', 'Drive up from dead stop', 'Lower back to pins'],
 ARRAY['Each rep starts fresh', 'Explosive drive', 'Full lockout'],
 ARRAY['Not fully stopping', 'Poor setup', 'Pins too high/low'],
 ARRAY['quads', 'glutes'], ARRAY['core', 'hamstrings'], ARRAY['barbell', 'power rack'],
 'advanced', 'squat', 'strength', 'https://v2.exercisedb.io/image/irKpNxLe0TW8rd', false, true, true),

('Floor Press', 'floor-press-compound', 'Bench press from floor for lockout strength.',
 ARRAY['Lie on floor with barbell', 'Lower until triceps touch floor', 'Pause briefly', 'Press up to lockout'],
 ARRAY['Dead stop at bottom', 'Explosive press', 'Full lockout'],
 ARRAY['Bouncing triceps', 'Not pausing', 'Bar path issues'],
 ARRAY['triceps', 'chest'], ARRAY['anterior deltoid'], ARRAY['barbell', 'dumbbells'],
 'intermediate', 'push', 'strength', 'https://v2.exercisedb.io/image/jrKpNxLe0TW8rd', false, true, true),

('Paused Bench Press', 'paused-bench-press', 'Bench press with pause on chest.',
 ARRAY['Lower bar to chest', 'Pause 1-2 seconds maintaining tension', 'Press explosively', 'Complete lockout'],
 ARRAY['Stay tight during pause', 'Bar stays still', 'Explosive drive'],
 ARRAY['Bouncing', 'Losing tension', 'Short pause'],
 ARRAY['chest'], ARRAY['triceps', 'anterior deltoid'], ARRAY['barbell', 'bench'],
 'intermediate', 'push', 'strength', 'https://v2.exercisedb.io/image/krKpNxLe0TW8rd', false, true, true),

('Tempo Squat', 'tempo-squat', 'Squat with controlled tempo for time under tension.',
 ARRAY['Descend slowly 3-4 seconds', 'Pause briefly at bottom', 'Drive up controlled', 'Brief pause at top'],
 ARRAY['Count tempo', 'Stay tight throughout', 'Maintain form'],
 ARRAY['Rushing', 'Not following tempo', 'Form breakdown'],
 ARRAY['quads', 'glutes'], ARRAY['core', 'hamstrings'], ARRAY['barbell'],
 'intermediate', 'squat', 'strength', 'https://v2.exercisedb.io/image/lrKpNxLe0TW8rd', false, true, true);

-- ============================================
-- WARMUP & MOBILITY (25)
-- ============================================

INSERT INTO exercises (name, slug, description, instructions, cues, common_mistakes, primary_muscles, secondary_muscles, equipment_names, difficulty, movement_pattern, exercise_type, video_url, is_machine, is_bilateral, is_published)
VALUES
('Arm Circles', 'arm-circles', 'Dynamic shoulder warmup.',
 ARRAY['Stand with arms extended', 'Make small circles gradually larger', 'Forward and backward', '30 seconds each direction'],
 ARRAY['Start small get bigger', 'Maintain posture', 'Full range'],
 ARRAY['Going too fast', 'Not full range', 'Poor posture'],
 ARRAY['shoulders'], ARRAY['rotator cuff'], ARRAY['bodyweight'],
 'beginner', 'isolation', 'warmup', 'https://v2.exercisedb.io/image/mrKpNxLe0TW8rd', false, true, true),

('Leg Swings', 'leg-swings', 'Dynamic hip mobility warmup.',
 ARRAY['Hold wall for balance', 'Swing leg forward and back', 'Then side to side', 'Increase range gradually'],
 ARRAY['Control the swing', 'Keep torso stable', 'Full range'],
 ARRAY['Swinging too hard', 'Poor balance', 'Not warming up'],
 ARRAY['hip flexors', 'glutes'], ARRAY['hamstrings', 'adductors'], ARRAY['bodyweight'],
 'beginner', 'isolation', 'warmup', 'https://v2.exercisedb.io/image/nrKpNxLe0TW8rd', false, false, true),

('Hip Circles', 'hip-circles', 'Dynamic hip mobility.',
 ARRAY['Stand on one leg', 'Make circles with other knee', 'Forward and backward', 'Switch legs'],
 ARRAY['Controlled circles', 'Full range', 'Stay balanced'],
 ARRAY['Rushing', 'Small range', 'Poor balance'],
 ARRAY['hip flexors'], ARRAY['glutes', 'core'], ARRAY['bodyweight'],
 'beginner', 'isolation', 'warmup', 'https://v2.exercisedb.io/image/orKpNxLe0TW8rd', false, false, true),

('Cat Cow', 'cat-cow', 'Spinal mobility warmup.',
 ARRAY['Start on hands and knees', 'Arch back looking up (cow)', 'Round back tucking chin (cat)', 'Alternate smoothly'],
 ARRAY['Move through full range', 'Breathe with movement', 'Smooth transitions'],
 ARRAY['Rushing', 'Not full range', 'Holding breath'],
 ARRAY['spine', 'core'], ARRAY['back', 'abs'], ARRAY['bodyweight'],
 'beginner', 'core', 'warmup', 'https://v2.exercisedb.io/image/prKpNxLe0TW8rd', false, true, true),

('World Greatest Stretch', 'world-greatest-stretch', 'Full body mobility sequence.',
 ARRAY['Step into deep lunge', 'Place same side elbow to floor', 'Rotate and reach to sky', 'Push hips back to stretch hamstring'],
 ARRAY['Deep lunge', 'Full rotation', 'Feel the stretch'],
 ARRAY['Not deep enough', 'Rushing', 'Skipping positions'],
 ARRAY['hip flexors', 'thoracic spine', 'hamstrings'], ARRAY['glutes', 'shoulders'], ARRAY['bodyweight'],
 'beginner', 'isolation', 'warmup', 'https://v2.exercisedb.io/image/qrKpNxLe0TW8rd', false, false, true),

('90/90 Hip Stretch', 'ninety-ninety-hip-stretch', 'Deep hip mobility stretch.',
 ARRAY['Sit with both legs at 90 degrees', 'Front shin parallel to shoulders', 'Lean forward over front leg', 'Switch sides'],
 ARRAY['Stay upright initially', 'Feel hip stretch', 'Breathe into stretch'],
 ARRAY['Compensating with back', 'Not 90 degree angles', 'Forcing range'],
 ARRAY['hip rotators', 'glutes'], ARRAY['hip flexors'], ARRAY['bodyweight'],
 'intermediate', 'isolation', 'stretch', 'https://v2.exercisedb.io/image/rrKpNxLe0TW8rd', false, false, true),

('Couch Stretch', 'couch-stretch', 'Intense hip flexor and quad stretch.',
 ARRAY['Rear knee against wall or couch', 'Front foot forward in lunge', 'Stay upright squeezing glutes', 'Hold 1-2 minutes per side'],
 ARRAY['Squeeze glute of back leg', 'Stay vertical', 'Breathe through it'],
 ARRAY['Leaning forward', 'Not squeezing glute', 'Giving up too early'],
 ARRAY['hip flexors', 'quads'], ARRAY['glutes'], ARRAY['wall', 'couch'],
 'intermediate', 'isolation', 'stretch', 'https://v2.exercisedb.io/image/srKpNxLe0TW8rd', false, false, true),

('Pigeon Pose', 'pigeon-pose', 'Deep glute and hip stretch.',
 ARRAY['From all fours bring one knee forward', 'Shin angled across body', 'Extend back leg behind', 'Fold forward over front leg'],
 ARRAY['Feel glute stretch', 'Keep hips square', 'Breathe deeply'],
 ARRAY['Hips rotating', 'Forcing depth', 'Not supporting weight'],
 ARRAY['glutes', 'hip rotators'], ARRAY['hip flexors'], ARRAY['bodyweight'],
 'intermediate', 'isolation', 'stretch', 'https://v2.exercisedb.io/image/trKpNxLe0TW8rd', false, false, true),

('Thread the Needle', 'thread-the-needle', 'Thoracic spine rotation stretch.',
 ARRAY['Start on hands and knees', 'Reach one arm under body', 'Let shoulder drop to floor', 'Return and reach to ceiling'],
 ARRAY['Big rotation', 'Breathe through it', 'Control movement'],
 ARRAY['Rushing', 'Not enough rotation', 'Moving hips'],
 ARRAY['thoracic spine'], ARRAY['shoulders', 'lats'], ARRAY['bodyweight'],
 'beginner', 'core', 'warmup', 'https://v2.exercisedb.io/image/urKpNxLe0TW8rd', false, false, true),

('Foam Roll Thoracic Spine', 'foam-roll-thoracic-spine', 'Thoracic extension mobilization.',
 ARRAY['Lie on foam roller at mid back', 'Support head with hands', 'Extend back over roller', 'Roll up and down thoracic spine'],
 ARRAY['Only thoracic not lower back', 'Extend over roller', 'Breathe and relax'],
 ARRAY['Rolling lower back', 'Not extending', 'Going too fast'],
 ARRAY['thoracic spine'], ARRAY['lats'], ARRAY['foam roller'],
 'beginner', 'core', 'warmup', 'https://v2.exercisedb.io/image/vrKpNxLe0TW8rd', false, true, true),

('Foam Roll Quads', 'foam-roll-quads', 'Quad self-myofascial release.',
 ARRAY['Lie face down with roller under quads', 'Roll from hip to knee', 'Pause on tender spots', 'Roll each leg separately'],
 ARRAY['Slow controlled rolling', 'Breathe through tension', 'Hit all quad areas'],
 ARRAY['Rolling too fast', 'Not enough pressure', 'Holding breath'],
 ARRAY['quads'], ARRAY[]::text[], ARRAY['foam roller'],
 'beginner', 'isolation', 'warmup', 'https://v2.exercisedb.io/image/wrKpNxLe0TW8rd', false, false, true),

('Foam Roll IT Band', 'foam-roll-it-band', 'IT band self-myofascial release.',
 ARRAY['Lie on side with roller under outer thigh', 'Roll from hip to knee', 'Stack or stagger legs for pressure', 'Pause on tender spots'],
 ARRAY['Control the pressure', 'Breathe steadily', 'Spend extra time on tight spots'],
 ARRAY['Rolling too fast', 'Too much pressure', 'Tensing up'],
 ARRAY['IT band', 'TFL'], ARRAY[]::text[], ARRAY['foam roller'],
 'beginner', 'isolation', 'warmup', 'https://v2.exercisedb.io/image/xrKpNxLe0TW8rd', false, false, true),

('Foam Roll Lats', 'foam-roll-lats', 'Lat self-myofascial release.',
 ARRAY['Lie on side with roller under armpit area', 'Roll from armpit to mid ribs', 'Thumb up position', 'Pause on tender spots'],
 ARRAY['Slow controlled rolling', 'Arm extended or bent', 'Breathe through it'],
 ARRAY['Rolling too fast', 'Missing lat tissue', 'Poor position'],
 ARRAY['lats'], ARRAY['teres major'], ARRAY['foam roller'],
 'beginner', 'isolation', 'warmup', 'https://v2.exercisedb.io/image/yrKpNxLe0TW8rd', false, false, true),

('Band Pull Apart', 'band-pull-apart', 'Rear delt and upper back warmup.',
 ARRAY['Hold band at shoulder width', 'Arms straight in front', 'Pull apart until band touches chest', 'Return with control'],
 ARRAY['Squeeze shoulder blades', 'Keep arms straight', 'Control return'],
 ARRAY['Bending arms', 'Using momentum', 'Not full range'],
 ARRAY['rear deltoid', 'rhomboids'], ARRAY['traps', 'rotator cuff'], ARRAY['resistance band'],
 'beginner', 'pull', 'warmup', 'https://v2.exercisedb.io/image/zrKpNxLe0TW8rd', false, true, true),

('Band Dislocates', 'band-dislocates', 'Shoulder mobility with band.',
 ARRAY['Hold band wide overhand grip', 'Keep arms straight', 'Bring band overhead and behind', 'Return to front'],
 ARRAY['Arms stay straight', 'Widen grip if needed', 'Smooth controlled motion'],
 ARRAY['Bending arms', 'Grip too narrow', 'Rushing'],
 ARRAY['shoulders', 'rotator cuff'], ARRAY['chest', 'lats'], ARRAY['resistance band', 'PVC pipe'],
 'beginner', 'isolation', 'warmup', 'https://v2.exercisedb.io/image/0sKpNxLe0TW8rd', false, true, true),

('Glute Bridge Hold', 'glute-bridge-hold', 'Glute activation warmup.',
 ARRAY['Lie on back knees bent', 'Drive hips up squeezing glutes', 'Hold at top for 30 seconds', 'Lower and repeat'],
 ARRAY['Squeeze glutes hard', 'Dont hyperextend', 'Breathe normally'],
 ARRAY['Using hamstrings only', 'Hyperextending back', 'Not squeezing enough'],
 ARRAY['glutes'], ARRAY['hamstrings', 'core'], ARRAY['bodyweight'],
 'beginner', 'hinge', 'warmup', 'https://v2.exercisedb.io/image/1sKpNxLe0TW8rd', false, true, true),

('Clamshell', 'clamshell', 'Glute medius activation.',
 ARRAY['Lie on side knees bent at 45 degrees', 'Keep feet together', 'Raise top knee up', 'Lower with control'],
 ARRAY['Dont rotate hips', 'Feel glute med working', 'Control the motion'],
 ARRAY['Rotating hips', 'Using momentum', 'Not squeezing'],
 ARRAY['glute medius'], ARRAY['hip rotators'], ARRAY['bodyweight', 'band'],
 'beginner', 'isolation', 'warmup', 'https://v2.exercisedb.io/image/2sKpNxLe0TW8rd', false, false, true),

('Fire Hydrant', 'fire-hydrant', 'Hip abductor and glute warmup.',
 ARRAY['Start on hands and knees', 'Raise one leg out to side keeping knee bent', 'Squeeze at top', 'Lower and repeat'],
 ARRAY['Minimal torso movement', 'Squeeze glute at top', 'Control throughout'],
 ARRAY['Rotating torso', 'Rushing', 'Not squeezing'],
 ARRAY['glute medius', 'hip abductors'], ARRAY['core'], ARRAY['bodyweight'],
 'beginner', 'isolation', 'warmup', 'https://v2.exercisedb.io/image/3sKpNxLe0TW8rd', false, false, true),

('Lying Spinal Twist', 'lying-spinal-twist', 'Gentle spinal rotation stretch.',
 ARRAY['Lie on back with arms out', 'Bring one knee across body', 'Look opposite direction', 'Hold and breathe'],
 ARRAY['Keep shoulders on floor', 'Breathe deeply', 'Relax into stretch'],
 ARRAY['Forcing range', 'Shoulder lifting', 'Holding breath'],
 ARRAY['spine', 'obliques'], ARRAY['glutes', 'IT band'], ARRAY['bodyweight'],
 'beginner', 'core', 'stretch', 'https://v2.exercisedb.io/image/4sKpNxLe0TW8rd', false, false, true),

('Child Pose', 'child-pose', 'Recovery and lat stretch.',
 ARRAY['Kneel on floor sitting on heels', 'Fold forward reaching arms ahead', 'Rest forehead on floor', 'Breathe deeply'],
 ARRAY['Reach fingers forward', 'Sink hips back', 'Relax completely'],
 ARRAY['Not reaching far enough', 'Tight hips limiting range', 'Not relaxing'],
 ARRAY['lats', 'lower back'], ARRAY['shoulders', 'hips'], ARRAY['bodyweight'],
 'beginner', 'isolation', 'stretch', 'https://v2.exercisedb.io/image/5sKpNxLe0TW8rd', false, true, true),

('Downward Dog', 'downward-dog', 'Full body stretch and hamstring mobility.',
 ARRAY['Start in plank position', 'Push hips up and back', 'Heels reach toward floor', 'Head between arms'],
 ARRAY['Straight back', 'Press through shoulders', 'Pedal feet if tight'],
 ARRAY['Rounding back', 'Not pressing through shoulders', 'Forcing heels down'],
 ARRAY['hamstrings', 'calves', 'shoulders'], ARRAY['lats', 'core'], ARRAY['bodyweight'],
 'beginner', 'isolation', 'stretch', 'https://v2.exercisedb.io/image/6sKpNxLe0TW8rd', false, true, true),

('Standing Quad Stretch', 'standing-quad-stretch', 'Classic quad stretch.',
 ARRAY['Stand on one leg', 'Grab ankle behind you', 'Pull heel toward glute', 'Keep knees together'],
 ARRAY['Knees together', 'Stand tall', 'Feel quad stretch'],
 ARRAY['Arching back', 'Knee flaring out', 'Poor balance'],
 ARRAY['quads'], ARRAY['hip flexors'], ARRAY['bodyweight'],
 'beginner', 'isolation', 'stretch', 'https://v2.exercisedb.io/image/7sKpNxLe0TW8rd', false, false, true),

('Hamstring Stretch', 'hamstring-stretch', 'Standing or seated hamstring stretch.',
 ARRAY['Stand with one leg on elevated surface', 'Keep leg straight', 'Hinge forward at hips', 'Hold and breathe'],
 ARRAY['Hinge at hips not back', 'Keep leg straight', 'Feel stretch in hamstring'],
 ARRAY['Rounding back', 'Bending knee', 'Forcing depth'],
 ARRAY['hamstrings'], ARRAY['calves'], ARRAY['bodyweight', 'bench'],
 'beginner', 'isolation', 'stretch', 'https://v2.exercisedb.io/image/8sKpNxLe0TW8rd', false, false, true),

('Hip Flexor Stretch', 'hip-flexor-stretch', 'Kneeling or standing hip flexor stretch.',
 ARRAY['Kneel on one knee', 'Front foot flat on floor', 'Push hips forward squeezing back glute', 'Hold and breathe'],
 ARRAY['Squeeze glute of back leg', 'Tall posture', 'Push hips forward not down'],
 ARRAY['Arching lower back', 'Not squeezing glute', 'Leaning forward'],
 ARRAY['hip flexors'], ARRAY['quads'], ARRAY['bodyweight'],
 'beginner', 'isolation', 'stretch', 'https://v2.exercisedb.io/image/9sKpNxLe0TW8rd', false, false, true),

('Shoulder Stretch', 'shoulder-stretch', 'Cross body shoulder stretch.',
 ARRAY['Bring one arm across body', 'Use other arm to pull it close', 'Keep shoulder down', 'Hold and breathe'],
 ARRAY['Shoulder stays down', 'Gentle pull', 'Feel stretch in rear delt'],
 ARRAY['Shrugging shoulder', 'Pulling too hard', 'Holding breath'],
 ARRAY['rear deltoid'], ARRAY['rotator cuff'], ARRAY['bodyweight'],
 'beginner', 'isolation', 'stretch', 'https://v2.exercisedb.io/image/asKpNxLe0TW8rd', false, false, true);

-- ============================================
-- FOREARM & GRIP (10)
-- ============================================

INSERT INTO exercises (name, slug, description, instructions, cues, common_mistakes, primary_muscles, secondary_muscles, equipment_names, difficulty, movement_pattern, exercise_type, video_url, is_machine, is_bilateral, is_published)
VALUES
('Wrist Curl', 'wrist-curl', 'Forearm flexor isolation.',
 ARRAY['Sit with forearms on thighs', 'Hold bar with palms up', 'Curl wrists up', 'Lower with control'],
 ARRAY['Only wrists move', 'Full range', 'Squeeze at top'],
 ARRAY['Moving arms', 'Going too heavy', 'Partial range'],
 ARRAY['forearm flexors'], ARRAY[]::text[], ARRAY['barbell', 'dumbbells'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/bsKpNxLe0TW8rd', false, true, true),

('Reverse Wrist Curl', 'reverse-wrist-curl', 'Forearm extensor isolation.',
 ARRAY['Sit with forearms on thighs', 'Hold bar with palms down', 'Curl wrists up', 'Lower with control'],
 ARRAY['Only wrists move', 'Full range', 'Control throughout'],
 ARRAY['Moving arms', 'Going too heavy', 'Rushing'],
 ARRAY['forearm extensors'], ARRAY[]::text[], ARRAY['barbell', 'dumbbells'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/csKpNxLe0TW8rd', false, true, true),

('Plate Pinch', 'plate-pinch', 'Grip strength exercise.',
 ARRAY['Pinch two plates together smooth side out', 'Hold for time', 'Grip with fingers not palm', 'Drop carefully'],
 ARRAY['Pinch hard', 'Breathe normally', 'Keep tension'],
 ARRAY['Using palm', 'Plates too heavy', 'Dropping unsafely'],
 ARRAY['forearms', 'fingers'], ARRAY[]::text[], ARRAY['weight plates'],
 'intermediate', 'isolation', 'strength', 'https://v2.exercisedb.io/image/dsKpNxLe0TW8rd', false, true, true),

('Dead Hang', 'dead-hang', 'Grip endurance and shoulder decompression.',
 ARRAY['Hang from pull-up bar', 'Arms fully extended', 'Hold as long as possible', 'Control descent'],
 ARRAY['Relax shoulders initially', 'Grip tight', 'Breathe normally'],
 ARRAY['Bending arms', 'Holding breath', 'Dropping suddenly'],
 ARRAY['forearms', 'grip'], ARRAY['shoulders', 'lats'], ARRAY['pull-up bar'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/esKpNxLe0TW8rd', false, true, true),

('Towel Pull-up', 'towel-pull-up', 'Pull-up with grip challenge.',
 ARRAY['Drape towel over pull-up bar', 'Grip towel ends', 'Perform pull-up', 'Lower with control'],
 ARRAY['Crush grip on towel', 'Pull chin over bar', 'Control descent'],
 ARRAY['Weak grip', 'Swinging', 'Partial reps'],
 ARRAY['lats', 'forearms'], ARRAY['biceps', 'rear deltoid'], ARRAY['pull-up bar', 'towel'],
 'advanced', 'pull', 'strength', 'https://v2.exercisedb.io/image/fsKpNxLe0TW8rd', false, true, true),

('Gripper Crush', 'gripper-crush', 'Hand gripper for crushing strength.',
 ARRAY['Hold gripper in one hand', 'Squeeze handles together', 'Control release', 'Repeat for reps'],
 ARRAY['Full close if possible', 'Control negative', 'Consistent form'],
 ARRAY['Incomplete close', 'Rushing', 'Only using finger strength'],
 ARRAY['forearms', 'fingers'], ARRAY[]::text[], ARRAY['hand gripper'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/gsKpNxLe0TW8rd', false, false, true),

('Finger Curl', 'finger-curl', 'Finger and grip strength exercise.',
 ARRAY['Hold bar at fingertips', 'Let bar roll to fingers', 'Curl fingers up bringing bar to palm', 'Lower with control'],
 ARRAY['Start at fingertips', 'Curl up fully', 'Control descent'],
 ARRAY['Using wrist', 'Bar slipping', 'Too heavy'],
 ARRAY['forearm flexors', 'fingers'], ARRAY[]::text[], ARRAY['barbell'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/hsKpNxLe0TW8rd', false, true, true),

('Wrist Roller', 'wrist-roller', 'Forearm endurance exercise.',
 ARRAY['Hold wrist roller with arms extended', 'Roll weight up by rotating wrists', 'Roll back down with control', 'Keep arms extended'],
 ARRAY['Arms stay extended', 'Alternate roll direction', 'Feel the burn'],
 ARRAY['Arms bending', 'Going too fast', 'Weight too heavy'],
 ARRAY['forearms'], ARRAY[]::text[], ARRAY['wrist roller'],
 'intermediate', 'isolation', 'strength', 'https://v2.exercisedb.io/image/isKpNxLe0TW8rd', false, true, true),

('Barbell Hold', 'barbell-hold', 'Static grip hold for endurance.',
 ARRAY['Hold barbell at thighs', 'Double overhand grip', 'Hold for time', 'Set down with control'],
 ARRAY['Squeeze hard', 'Stand tall', 'Breathe normally'],
 ARRAY['Mixed grip defeating purpose', 'Poor posture', 'Dropping bar'],
 ARRAY['forearms', 'grip'], ARRAY['traps'], ARRAY['barbell'],
 'beginner', 'isolation', 'strength', 'https://v2.exercisedb.io/image/jsKpNxLe0TW8rd', false, true, true),

('Fat Grip Training', 'fat-grip-training', 'Thick bar training for grip strength.',
 ARRAY['Attach fat grips to bar or dumbbells', 'Perform any exercise', 'Extra grip challenge', 'Use lighter weight'],
 ARRAY['Squeeze hard throughout', 'Reduce weight from normal', 'Focus on grip'],
 ARRAY['Going too heavy', 'Losing grip mid set', 'Not adjusting weight'],
 ARRAY['forearms'], ARRAY['varies by exercise'], ARRAY['fat grips', 'barbell', 'dumbbells'],
 'intermediate', 'isolation', 'strength', 'https://v2.exercisedb.io/image/ksKpNxLe0TW8rd', false, true, true);

